[tool.poetry]
name = "hangoutcore"
version = "0.1.0"
description = ""
authors = ["Lino <hutchinsl0507@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
